In [1]:
! pip install numpy
! pip install pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.9/16.9 MB 76.0 MB/s eta 0:00:00:00:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.1/11.1 MB 66.7 MB/s eta 0:00:0000:010:01


In [16]:
import numpy as np 
import pandas as pd

In [37]:
import importlib
import battery_analysis as ba

importlib.reload(ba)

<module 'battery_analysis' from '/home/coderpad/app/battery_analysis.py'>

In [38]:
voltage_1 = [4.20, 4.10, 4.00, 3.85, 3.70]
voltage_2 = [4.15, 4.05, 3.95, 3.80, 3.60]

In [39]:
test1=ba.create_test('cell_001',voltage_1)
test2=ba.create_test('cell_002',voltage_2)

In [40]:
type(test1)

battery_analysis.BatteryTest

In [41]:
test3=ba.BatteryTest('cell3',voltage_1)

In [42]:
test1.average_voltage()

np.float64(3.97)

In [43]:
ba.compare_max_voltage(test1,test2)

cell_001 has the highest maximum voltage


In [44]:
dir(ba)

['BatteryTest',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'compare_average',
 'compare_max_voltage',
 'count_total_measurements',
 'create_test',
 'find_lowest_voltage',
 'get_voltage_shape',
 'np']

In [33]:
dir(test1)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'average_voltage',
 'below_threshold',
 'count_below_threshold',
 'name',
 'normalize',
 'voltage',
 'voltage_range']

In [45]:
dir(ba.BatteryTest.average_voltage)

['__annotations__',
 '__builtins__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__getstate__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [46]:
ba.BatteryTest.average_voltage??

Signature: ba.BatteryTest.average_voltage(self)
Docstring: <no docstring>
Source:   
    def average_voltage(self):
        aver = np.mean(self.voltage)
        return aver
File:      ~/app/battery_analysis.py
Type:      function

In [47]:
list(np.array([1,2,3,4,5]).shape)

[5]

In [48]:
a=np.array([[1,2],[3,4]])

In [49]:
a.shape

(2, 2)

In [5]:
a.dtype

dtype('int64')

In [6]:
a.ndim

2

In [7]:
a.size

4

In [8]:
a.item

<function ndarray.item(*args)>

In [9]:
a.itemsize

8

In [10]:
a.shape[0]

2

In [11]:
a.shape[1]

2

In [12]:
a.sum()

np.int64(10)

In [13]:
a.mean()

np.float64(2.5)

In [14]:
a.min()

np.int64(1)

In [15]:
a.max()

np.int64(4)

In [16]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [17]:
b.ndim

2

In [18]:
b.shape

(3, 3)

In [19]:
b.sum()

np.int64(45)

In [20]:
b[1,1]

np.int64(5)

In [21]:
b.itemsize

8

In [33]:
b=b.flatten()

In [23]:
a.T

array([[1, 3],
       [2, 4]])

In [31]:
a=a.flatten()

In [34]:
a.shape
b.shape

(9,)

In [37]:
c=np.concatenate([a,b])
c.shape

(13,)

In [38]:
c=['a','b','c']

In [39]:
dir(c)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [40]:
type(c)

list

In [41]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '_

In [44]:
df1=pd.DataFrame(
    {
        'Name': ['Liyuan','Brett','Ginn'],
        'Score': [70,80,90]
    }
)

In [45]:
dir(df1)

['Name',
 'Score',
 'T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__'

In [46]:
callable(df1.var)

True

In [47]:
callable(df1.to_xarray)

True

In [48]:
callable(df1.dtypes)

False

In [20]:
class student: 
    def __init__(self,name,score):
        self.name=name
        self.score=score

    def score_grad(self,thred):
        if self.score>thred:
            return 'A'
        else:
            return 'B'


student1= student('Liyuan', 59)
student1.score
student1.score_grad(thred=60)

student2=student('Brett',69)
student2.score
student2.score_grad(thred=70)

dir(student1)
dir(student)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'score_grad']

In [16]:
dir(student)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'score_grad']

In [21]:
type(student)

type

In [22]:
type(student1)

__main__.student

In [29]:
type(pd.DataFrame)

type

In [30]:
callable(student1.score)

False

In [14]:
import pandas as pd 

## practice case studies: battery sensor analysis 

In [17]:
import numpy as np

voltage_1 = np.array([4.20, 4.10, 4.00, 3.85, 3.70])
voltage_2 = np.array([4.15, 4.05, 3.95, 3.80, 3.60])
voltage_3 = np.array([4.25, 4.12, 4.02, 3.90, 3.75])

In [91]:
class BatteryTest:
    def __init__(self,name,voltage):
        self.name=name
        self.voltage=np.array(voltage)

    def average_voltage(self):
        aver=np.mean(self.voltage)
        return aver

    def voltage_range(self):
        a ={
            'min':np.min(self.voltage),
            'max':np.max(self.voltage)
        }
        return a

    def below_threshold(self,threshold):
        return self.voltage[self.voltage<threshold]

    def count_below_threshold(self,threshold):
        return np.sum(self.voltage<threshold)

    def normalize(self):
        x_norm=(self.voltage-np.min(self.voltage))/(np.max(self.voltage)-np.min(self.voltage))
        return x_norm 




    




In [92]:
test1=BatteryTest('Cell_1',voltage_1)

In [93]:
type(test1)

__main__.BatteryTest

In [94]:
type(test1.voltage)

numpy.ndarray

In [95]:
type(test1.average_voltage)

method

In [96]:
test1.average_voltage()

np.float64(3.97)

In [97]:
test1.voltage_range()

{'min': np.float64(3.7), 'max': np.float64(4.2)}

In [98]:
test1.below_threshold(4.0)

array([3.85, 3.7 ])

In [99]:
test1.count_below_threshold(4.0)

np.int64(2)

In [100]:
test1.normalize()

array([1. , 0.8, 0.6, 0.3, 0. ])

In [101]:
dir(BatteryTest)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'average_voltage',
 'below_threshold',
 'count_below_threshold',
 'normalize',
 'voltage_range']

In [102]:
dir(test1)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'average_voltage',
 'below_threshold',
 'count_below_threshold',
 'name',
 'normalize',
 'voltage',
 'voltage_range']

In [103]:
callable(test1.name)

False

In [104]:
import battery_analysis as ba


In [105]:
voltage_1=np.array([4.2,4.1,4.0,3.85,3.7])
test1=ba.create_test('cell_001',voltage_1)

In [106]:
type(test1)

battery_analysis.BatteryTest

In [107]:
type(BatteryTest)

type

In [109]:
type(ba)

module